-- Data awal (konten contoh). Harga masih CONTOH, ganti lewat panel admin / SQL.
insert into public.vehicles (slug, name, category, subtitle, seats, transmission, image_url, tint, badge, price_per_day, price_with_driver, highlights, included, sort) values
  ('honda-scoopy', 'Honda Scoopy', 'scooter', 'Scooter · 110cc · Automatic', 2, 'Automatic', '/images/placeholder/scooter-cream.svg', 'bg-sun-soft', 'Most popular', 90000, null, array['2 riders', '2 helmets']::text[], array['2 helmets', '2 rain ponchos', 'Phone holder', 'Basic insurance', 'Free delivery in Canggu, Seminyak, Kuta & Ubud']::text[], 0),
  ('yamaha-nmax', 'Yamaha NMAX', 'scooter', 'Maxi scooter · 155cc · Automatic', 2, 'Automatic', '/images/placeholder/scooter-navy.svg', 'bg-mist', null, 150000, null, array['2 riders', 'Big storage']::text[], array['2 helmets', '2 rain ponchos', 'Phone holder', 'Basic insurance', 'Free delivery in Canggu, Seminyak, Kuta & Ubud']::text[], 1),
  ('toyota-avanza', 'Toyota Avanza', 'car', 'MPV · 7 seats · Automatic', 7, 'Automatic', '/images/placeholder/car-silver.svg', 'bg-sky-soft', null, 350000, 650000, array['7 seats', 'Driver optional']::text[], array['Full tank on delivery', 'Basic insurance', 'Child seat on request', '24/7 roadside help']::text[], 2),
  ('toyota-innova-zenix', 'Toyota Innova Zenix', 'car', 'Premium MPV · 7 seats · with driver', 6, 'Automatic', '/images/placeholder/car-dark.svg', 'bg-leaf-soft', 'With driver', null, 850000, array['6 guests', 'English-speaking driver']::text[], array['English-speaking driver', 'Fuel for 10 hours', 'Mineral water', 'Parking fees', 'Child seat on request']::text[], 3);

insert into public.tours (slug, title, area, categories, duration, pickup, summary, facts, highlights, itinerary, included, excluded, price_from, badge, featured, sort) values
  ('nusa-penida-west', 'Nusa Penida West Island Tour', 'Nusa Penida', array['islands', 'beaches']::text[], 'Full day', 'Hotel pick-up 06:30', 'Fast boat from Sanur and a private car on the island. See Kelingking Beach, Broken Beach, Angel''s Billabong and Crystal Bay in one day.', array['Pick-up 06:30', 'Fast boat incl.', 'Lunch & tickets', 'Free cancel 24 h']::text[], '[{"name":"Kelingking Beach","image":"/images/placeholder/cliff.svg","position":"80% 50%"},{"name":"Crystal Bay","image":"/images/placeholder/beach.svg"},{"name":"Broken Beach","image":"/images/placeholder/cliff.svg","position":"20% 50%"},{"name":"Angel''s Billabong","image":"/images/placeholder/uluwatu.svg"}]'::jsonb, '[{"time":"06:30","title":"Pick-up from your hotel or villa"},{"time":"08:00","title":"Fast boat from Sanur to Nusa Penida"},{"time":"09:00","title":"Kelingking Beach viewpoint"},{"time":"11:00","title":"Broken Beach & Angel''s Billabong"},{"time":"13:00","title":"Lunch at a local warung"},{"time":"14:30","title":"Crystal Bay"},{"time":"16:30","title":"Fast boat back, drop-off at your hotel"}]'::jsonb, array['Hotel pick-up & drop-off', 'Return fast boat', 'Private car & driver on the island', 'Entrance fees', 'Lunch & mineral water']::text[], array['Snorkeling gear', 'Tips', 'Personal expenses']::text[], 950000, 'Best seller', true, 0),
  ('mount-batur-sunrise', 'Mount Batur Sunrise Trek', 'Kintamani', array['sunrise', 'nature']::text[], '8 hours', 'Hotel pick-up 02:00', 'An easy-to-moderate night hike to the top of an active volcano, with breakfast and a sea of clouds at sunrise.', array['Pick-up 02:00', 'Local guide', 'Breakfast at the top', 'Free cancel 24 h']::text[], '[{"name":"Summit sunrise","image":"/images/placeholder/batur.svg"},{"name":"Lake Batur view","image":"/images/placeholder/temple.svg"},{"name":"Coffee plantation","image":"/images/placeholder/terraces.svg"}]'::jsonb, '[{"time":"02:00","title":"Pick-up from your hotel"},{"time":"04:00","title":"Start the hike with a local guide"},{"time":"06:00","title":"Sunrise and breakfast at the summit"},{"time":"08:00","title":"Hike down, coffee plantation stop"},{"time":"10:30","title":"Drop-off at your hotel"}]'::jsonb, array['Hotel pick-up & drop-off', 'Certified local guide', 'Flashlight', 'Breakfast & water', 'Entrance fee']::text[], array['Hiking shoes', 'Tips']::text[], 650000, null, false, 1),
  ('uluwatu-sunset-kecak', 'Uluwatu Sunset & Kecak', 'Uluwatu', array['temples', 'beaches']::text[], 'Half day', 'Hotel pick-up 14:00', 'Cliff-top temple at sunset followed by the Kecak fire dance, with a stop at a white sand beach on the way.', array['Pick-up 14:00', 'Kecak tickets incl.', 'Private car', 'Free cancel 24 h']::text[], '[{"name":"Uluwatu Temple","image":"/images/placeholder/uluwatu.svg"},{"name":"Kecak fire dance","image":"/images/placeholder/uluwatu.svg","position":"80% 50%"},{"name":"Padang Padang Beach","image":"/images/placeholder/beach.svg"}]'::jsonb, '[{"time":"14:00","title":"Pick-up from your hotel"},{"time":"15:00","title":"Padang Padang Beach"},{"time":"17:00","title":"Uluwatu Temple at sunset"},{"time":"18:00","title":"Kecak fire dance"},{"time":"20:00","title":"Drop-off, or dinner at Jimbaran on request"}]'::jsonb, array['Private car & driver', 'Kecak tickets', 'Temple entrance & sarong', 'Mineral water']::text[], array['Dinner', 'Tips']::text[], 450000, null, false, 2),
  ('bedugul-lake-temple', 'Bedugul Lake Temple & Waterfalls', 'Bedugul', array['temples', 'nature']::text[], 'Full day', 'Hotel pick-up 08:00', 'Cool mountain air, Ulun Danu Beratan temple on the lake, twin waterfalls and a local fruit market.', array['Pick-up 08:00', 'Private car', 'Entrance fees incl.', 'Free cancel 24 h']::text[], '[{"name":"Ulun Danu Beratan","image":"/images/placeholder/temple.svg"},{"name":"Jatiluwih rice terraces","image":"/images/placeholder/terraces.svg"}]'::jsonb, '[{"time":"08:00","title":"Pick-up from your hotel"},{"time":"10:00","title":"Jatiluwih rice terraces"},{"time":"12:30","title":"Lunch with a lake view"},{"time":"14:00","title":"Ulun Danu Beratan temple"},{"time":"15:30","title":"Banyumala twin waterfalls"},{"time":"18:00","title":"Drop-off at your hotel"}]'::jsonb, array['Private car & driver', 'Entrance fees', 'Mineral water']::text[], array['Lunch', 'Tips']::text[], 550000, null, false, 3),
  ('canggu-surf-lesson', 'Canggu Surf Lesson', 'Canggu', array['beaches']::text[], '2 hours', 'Meet at Batu Bolong beach', 'Beginner-friendly lesson on soft-top boards with a certified instructor. Add a scooter with a surf rack for the rest of your stay.', array['2 hours', 'Board & rash guard', 'Certified instructor', 'Free cancel 24 h']::text[], '[{"name":"Batu Bolong beach","image":"/images/placeholder/beach.svg"}]'::jsonb, '[{"time":"0:00","title":"Warm-up and safety briefing on the sand"},{"time":"0:20","title":"Practice in the white water"},{"time":"1:45","title":"Photos and cool-down"}]'::jsonb, array['Soft-top board', 'Rash guard', 'Certified instructor', 'Mineral water']::text[], array['Transport (add a scooter or car)', 'Photos package']::text[], 400000, null, false, 4),
  ('ubud-highlights', 'Ubud Rice Terraces & Monkey Forest', 'Ubud', array['nature', 'temples']::text[], 'Full day', 'Hotel pick-up 08:30', 'Tegallalang rice terraces, the Sacred Monkey Forest, a water temple and Ubud art market with a private driver.', array['Pick-up 08:30', 'Private car', 'Entrance fees incl.', 'Free cancel 24 h']::text[], '[{"name":"Tegallalang","image":"/images/placeholder/terraces.svg"},{"name":"Water temple","image":"/images/placeholder/temple.svg"}]'::jsonb, '[{"time":"08:30","title":"Pick-up from your hotel"},{"time":"10:00","title":"Tegallalang rice terraces"},{"time":"12:00","title":"Lunch in Ubud"},{"time":"13:30","title":"Sacred Monkey Forest"},{"time":"15:00","title":"Ubud art market"},{"time":"17:30","title":"Drop-off at your hotel"}]'::jsonb, array['Private car & driver', 'Entrance fees', 'Mineral water']::text[], array['Lunch', 'Tips']::text[], 500000, null, false, 5);

insert into public.photos (scope, tour_id, url, alt, position, sort)
  select 'tour', id, '/images/placeholder/cliff.svg', 'Kelingking Beach viewpoint', null, 0 from public.tours where slug = 'nusa-penida-west'
union all
  select 'tour', id, '/images/placeholder/beach.svg', 'Crystal Bay', null, 1 from public.tours where slug = 'nusa-penida-west'
union all
  select 'tour', id, '/images/placeholder/cliff.svg', 'Broken Beach', '20% 50%', 2 from public.tours where slug = 'nusa-penida-west'
union all
  select 'tour', id, '/images/placeholder/uluwatu.svg', 'Sunset on the ride back', null, 3 from public.tours where slug = 'nusa-penida-west'
union all
  select 'tour', id, '/images/placeholder/beach.svg', 'Fast boat to Nusa Penida', '85% 50%', 4 from public.tours where slug = 'nusa-penida-west'
union all
  select 'tour', id, '/images/placeholder/batur.svg', 'Sunrise over Mount Batur', null, 0 from public.tours where slug = 'mount-batur-sunrise'
union all
  select 'tour', id, '/images/placeholder/terraces.svg', 'Coffee plantation stop', null, 1 from public.tours where slug = 'mount-batur-sunrise'
union all
  select 'tour', id, '/images/placeholder/temple.svg', 'Lake Batur in the morning', null, 2 from public.tours where slug = 'mount-batur-sunrise'
union all
  select 'tour', id, '/images/placeholder/uluwatu.svg', 'Uluwatu temple at sunset', null, 0 from public.tours where slug = 'uluwatu-sunset-kecak'
union all
  select 'tour', id, '/images/placeholder/beach.svg', 'Padang Padang beach', null, 1 from public.tours where slug = 'uluwatu-sunset-kecak'
union all
  select 'tour', id, '/images/placeholder/temple.svg', 'Ulun Danu Beratan temple', null, 0 from public.tours where slug = 'bedugul-lake-temple'
union all
  select 'tour', id, '/images/placeholder/terraces.svg', 'Jatiluwih rice terraces', null, 1 from public.tours where slug = 'bedugul-lake-temple'
union all
  select 'tour', id, '/images/placeholder/beach.svg', 'Batu Bolong beach', null, 0 from public.tours where slug = 'canggu-surf-lesson'
union all
  select 'tour', id, '/images/placeholder/terraces.svg', 'Tegallalang rice terraces', null, 0 from public.tours where slug = 'ubud-highlights'
union all
  select 'tour', id, '/images/placeholder/temple.svg', 'Water temple', null, 1 from public.tours where slug = 'ubud-highlights'
union all
  select 'hero', null::uuid, '/images/placeholder/hero.svg', 'Rice terraces near Ubud at sunset with Mount Agung behind', '70% 50%', 0
union all
  select 'hero', null::uuid, '/images/placeholder/cliff.svg', 'Kelingking Beach on Nusa Penida', null, 1
union all
  select 'hero', null::uuid, '/images/placeholder/batur.svg', 'Sunrise from Mount Batur', null, 2;
